apiVersion: v1
kind: ConfigMap
metadata:
  name: metro-config
data:
  COLLECTOR_TOTAL_SHARDS: "6"
  COLLECTOR_WINDOW_SECONDS: "10"
  COLLECTOR_EVENTS_PER_SECOND: "100"
  COLLECTOR_ARROW_ADDR: ":8080"
  COLLECTOR_ETCD_ENDPOINTS: "http://etcd:2379"
  COLLECTOR_NATS_URL: "nats://nats:4222"
  COLLECTOR_NATS_SUBJECT: "metro.passenger.windows"

